export const ROUTES: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  'nodes/custom-nodes': () => import('./demos/custom-nodes'),
  'nodes/html-nodes': () => import('./demos/html-nodes'),
  'nodes/node-resizer': () => import('./demos/node-resizer'),
  'nodes/auto-sizing': () => import('./demos/auto-sizing'),
  'nodes/connection-limit': () => import('./demos/connection-limit'),
  'nodes/delete-middle-node': () => import('./demos/delete-middle-node'),
  'nodes/drag-handle': () => import('./demos/drag-handle'),
  'nodes/easy-connect': () => import('./demos/easy-connect'),
  'nodes/intersections': () => import('./demos/intersections'),
  'nodes/node-position-animation': () => import('./demos/node-position-animation'),
  'nodes/node-resize-gesture': () => import('./demos/node-resize-gesture'),
  'nodes/node-toolbar': () => import('./demos/node-toolbar'),
  'nodes/proximity-connect': () => import('./demos/proximity-connect'),
  'nodes/rotatable-node': () => import('./demos/rotatable-node'),
  'nodes/shapes': () => import('./demos/shapes'),
  'nodes/stress-test': () => import('./demos/stress-test'),
  'nodes/updating-nodes': () => import('./demos/updating-nodes'),
  'edges/animating-edges': () => import('./demos/animating-edges'),
  'edges/custom-edges': () => import('./demos/custom-edges'),
  'edges/edge-labels': () => import('./demos/edge-labels'),
  'edges/edge-markers': () => import('./demos/edge-markers'),
  'edges/editable-edge': () => import('./demos/editable-edge'),
  'layout/elk-tree': () => import('./demos/elk-tree'),
  'misc/minimap-and-controls': () => import('./demos/minimap-and-controls'),
  'diagrams/class-uml': () => import('./demos/class-uml'),
  'diagrams/erd-editor': () => import('./demos/erd-editor'),
  'dashboard/dashboard-builder': () => import('./demos/dashboard-builder'),
  'collab/two-tabs-live': () => import('./demos/two-tabs-live'),
  'collab/comments': () => import('./demos/comments'),
  'misc/mermaid-text': () => import('./demos/mermaid-text'),
};
import type React from 'react';
