/* eslint-disable */
export default {
  displayName: 'qwik',
  preset: '../../jest.preset.js',
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.[tj]sx?$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json' }],
  },
  transformIgnorePatterns: ['node_modules/(?!(nanoid|uuid)/)'],
  moduleNameMapper: {
    '^nanoid$': '<rootDir>/../engine/src/__mocks__/nanoid.ts',
    '^uuid$': '<rootDir>/../engine/src/__mocks__/uuid.ts',
    // Virtual module generated by the Qwik Vite plugin; see the stub's header.
    '^@qwik-client-manifest$': '<rootDir>/src/__mocks__/qwik-client-manifest.ts',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'html'],
  coverageDirectory: '../../coverage/libs/qwik',
};
