import type { Component } from 'vue';
export const ROUTES: Record<string, () => Promise<{ default: Component }>> = {
  'nodes/custom-nodes': () => import('./demos/custom-nodes.vue'),
  'nodes/html-nodes': () => import('./demos/html-nodes.vue'),
  'nodes/node-resizer': () => import('./demos/node-resizer.vue'),
  'nodes/auto-sizing': () => import('./demos/auto-sizing.vue'),
  'nodes/connection-limit': () => import('./demos/connection-limit.vue'),
  'nodes/delete-middle-node': () => import('./demos/delete-middle-node.vue'),
  'nodes/drag-handle': () => import('./demos/drag-handle.vue'),
  'nodes/easy-connect': () => import('./demos/easy-connect.vue'),
  'nodes/intersections': () => import('./demos/intersections.vue'),
  'nodes/node-position-animation': () => import('./demos/node-position-animation.vue'),
  'nodes/node-resize-gesture': () => import('./demos/node-resize-gesture.vue'),
  'nodes/node-toolbar': () => import('./demos/node-toolbar.vue'),
  'nodes/proximity-connect': () => import('./demos/proximity-connect.vue'),
  'nodes/rotatable-node': () => import('./demos/rotatable-node.vue'),
  'nodes/shapes': () => import('./demos/shapes.vue'),
  'nodes/stress-test': () => import('./demos/stress-test.vue'),
  'nodes/updating-nodes': () => import('./demos/updating-nodes.vue'),
  'edges/editable-edge': () => import('./demos/editable-edge.vue'),
  'edges/animating-edges': () => import('./demos/animating-edges.vue'),
  'edges/custom-edges': () => import('./demos/custom-edges.vue'),
  'edges/edge-labels': () => import('./demos/edge-labels.vue'),
  'edges/edge-markers': () => import('./demos/edge-markers.vue'),
  'layout/elk-tree': () => import('./demos/elk-tree.vue'),
  'misc/minimap-and-controls': () => import('./demos/minimap-and-controls.vue'),
  'diagrams/class-uml': () => import('./demos/class-uml.vue'),
  'diagrams/erd-editor': () => import('./demos/erd-editor.vue'),
  'dashboard/dashboard-builder': () => import('./demos/dashboard-builder.vue'),
  'collab/two-tabs-live': () => import('./demos/two-tabs-live.vue'),
  'collab/comments': () => import('./demos/comments.vue'),
  'misc/mermaid-text': () => import('./demos/mermaid-text.vue'),
};
